name: build.yml

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Integrate ckeditor
        run: cd ckeditor5 && npm i && npm run build 

      - name: Back to project directory
        run: cd ..

      - name: Install dependencies
        run: npm install

      - name: Build source
        run: npm run build

      - name: Check lint
        run: npm run lint
